//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Detectorgui.rc
//
#define IDD_DETECTOR_GUI_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDB_FULL_BT_LOGO_PNG            130
#define IDB_PNG1                        133
#define IDB_PNG2                        134
#define IDD_DIALOG_STATUS               135
#define IDD_DIALOG_PLOT                 137
#define IDD_DIALOG_SETUP                139
#define IDD_DIALOG_CAL_PASS_FAIL        140
#define IDD_DIALOG_CAL_CELL             141
#define IDI_ICON_FOLDER_OPEN            142
#define IDD_DIALOG_STABILIZING          142
#define IDR_ACCELERATOR_IGNORE_KEYS     143
#define IDD_DIALOG_FILE_SAVE_MSG        143
#define IDD_DIALOG_SURVEY_NAME_MSG      144
#define IDD_DIALOG_GPS_FIX              145
#define IDD_DIALOG_SURVEY_KML_SAVE      146
#define IDB_BITMAP_1                    146
#define IDD_DIALOG_ALARM                147
#define IDB_BITMAP_2                    147
#define IDB_BITMAP_3                    148
#define IDD_DIALOG_EXPORT_KML           148
#define IDR_ACCELERATOR1                148
#define IDR_ACCELERATOR_SECRET          148
#define IDB_BITMAP_4                    149
#define IDD_DIALOG_MESSAGE_BOX_OK_CANCEL 149
#define IDR_ACCELERATOR2                149
#define IDB_BITMAP_5                    150
#define IDB_BITMAP_6                    151
#define IDD_DIALOG_BLUETOOTH_DATA       151
#define IDB_BITMAP_7                    152
#define IDB_BITMAP_8                    153
#define IDD_DIALOG_PLEASE_WAIT          153
#define IDB_BITMAP_9                    154
#define IDB_BITMAP_0                    155
#define IDD_DIALOG_SELECT_BT            155
#define IDB_BITMAP_X                    156
#define IDB_BITMAP_CHECK                157
#define IDB_BITMAP_10                   158
#define IDB_BITMAP_BELL                 158
#define IDB_BITMAP_X1                   159
#define IDB_BITMAP_BUTTON_TEST          159
#define IDC_BUTTON_SETUP                1001
#define IDC_STATIC_ALIGN                1002
#define IDC_BUTTON_START_STOP           1003
#define IDC_BUTTON_LOG_DATA             1004
#define IDC_BUTTON_CALIBRATE            1005
#define IDC_BUTTON_ALARM_SET            1006
#define IDC_BUTTON_PROCEED              1006
#define IDC_BUTTON_ALARM_SET2           1007
#define IDC_BUTTON_EXPORT_KLM           1007
#define IDC_STATIC_LOGO                 1008
#define IDC_STATIC_STATUS               1009
#define IDC_STATIC_STATUS_MSG           1010
#define IDC_CHECK1                      1011
#define IDC_CHECK_LASER                 1011
#define IDC_CHECK_SUB_BACKGROUND        1011
#define IDC_CHECK_BLUETHOOTH            1012
#define IDC_CHECK_24H_CLOCK             1012
#define IDC_CHECK_DATE                  1013
#define IDC_CHECK2                      1014
#define IDC_CHECK_GPS                   1014
#define IDC_CHECK_TIME                  1014
#define IDC_CHECK_BATTERY               1015
#define IDC_CUSTOM_PLOT                 1015
#define IDC_STATIC_NUM_PPM              1016
#define IDC_STATIC_PPM                  1017
#define IDC_STATIC_LAT_TEXT             1018
#define IDC_STATIC_LONG_TEXT            1019
#define IDC_STATIC_VERSION              1019
#define IDC_STATIC_SURVEY               1020
#define IDC_STATIC_CAL_DATA             1021
#define IDC_STATIC_ALARM_LEVEL          1022
#define IDC_STATIC_XAXIS                1023
#define IDC_STATIC_FILENAME             1024
#define IDC_STATIC_CSV                  1025
#define IDC_EDIT_SURVEY_PATH            1026
#define IDC_EDIT_CAL_PATH               1027
#define IDC_EDIT_ALARM_LEVEL            1028
#define IDC_STATIC_CAL_DUE              1029
#define IDC_EDIT_CAL_DUE                1030
#define IDC_BUTTON_OPEN_SURVEY_PATH     1031
#define IDC_STATIC_TEXT_LINE1           1032
#define IDC_BUTTON_OPEN_CAL_PATH        1032
#define IDC_STATIC_TEXT_LINE2           1033
#define IDC_STATIC_WAVE_FILE            1033
#define IDC_EDIT_WAVE_FILE              1034
#define IDC_STATIC_TEXT_LINE3           1034
#define IDC_BUTTON_WAV_FILE             1035
#define IDC_STATIC_FILENAME2            1036
#define IDC_EDIT2                       1037
#define IDC_EDIT_LOCATION               1037
#define IDC_STATIC_YAXIS                1038
#define IDC_EDIT_XAXIS                  1039
#define IDC_EDIT_XAXIS2                 1040
#define IDC_EDIT_YAXIS                  1040
#define IDC_EDIT1                       1042
#define IDC_EDIT_FILE_NAME              1042
#define IDC_EDIT_FILE_NAME2             1043
#define IDC_STATIC_LAST_PEAK            1045
#define IDC_STATIC_LAST_PEAK2           1046
#define IDC_STATIC_DISTANCE             1046
#define IDC_BUTTON_WAIT                 1046
#define IDC_BUTTON1                     1047
#define IDC_BUTTON_1                    1047
#define IDC_BUTTON_PAUSE                1047
#define IDC_BUTTON_DISPLAY              1047
#define IDC_BUTTON_UPDATE_FW            1047
#define IDC_BUTTON_SCAN_BT              1047
#define IDC_BUTTON_2                    1048
#define IDC_BUTTON_PAUSE2               1048
#define IDC_BUTTON_CLEAR                1048
#define IDC_BUTTON_3                    1049
#define IDC_BUTTON_4                    1050
#define IDC_BUTTON_5                    1051
#define IDC_BUTTON_6                    1052
#define IDC_BUTTON_7                    1053
#define IDC_BUTTON_8                    1054
#define IDC_BUTTON_9                    1055
#define IDC_BUTTON_0                    1056
#define IDC_BUTTON_X                    1057
#define IDC_BUTTON_CHECK                1058
#define IDC_BUTTON_10                   1059
#define IDC_SLIDER_VOLUME               1059
#define IDC_STATIC_BELL                 1060
#define IDC_BUTTON_TEST_VOLUME          1061
#define IDC_DATETIMEPICKER_STARTTIME    1063
#define IDC_STATIC_START_DATE           1064
#define IDC_STATIC_END_DATE             1065
#define IDC_DATETIMEPICKER_ENDTIME      1067
#define IDC_LIST_KML                    1075
#define IDC_STATIC_LOCATION             1077
#define IDC_BUTTON_OK                   1078
#define IDC_BUTTON_CANCEL               1079
#define IDC_LIST1                       1080
#define IDC_DebugWindow                 1080
#define IDC_LIST_DATA                   1080
#define IDC_STATIC_LAT                  1081
#define IDC_STATIC_LON                  1082
#define IDC_STATIC_LASTPEAK             1083
#define IDC_PROGRESS1                   1083
#define IDC_STATIC_PERCENT              1084
#define IDC_COMBO_BT_DEVICE             1085
#define IDC_STATIC_LASER_BLOCKED        1086
#define IDC_PROGRESS3                   1091
#define IDC_PROGRESS_STATUS             1091
#define ID_ACC_ENTER                    32771
#define ID_ACC_ESC                      32772
#define ID_ACCELERATOR_HIDDEN           32779
#define ID_ACCELERATOR_FW               32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
